Repository 1Alisha/HACKTOBERFEST-22, pull requests merged in 2022-10, with the labels that each got.

#20 Added cpp code to find number of islands using dfs
  DSA algoriths/Number_of_Islands.cpp
Labels: hactoberfest-accepted, hactoberfest2022, developer

#21 Create binary_search.py
  Sorting/binary_search.py
Labels: hactoberfest-accepted, hactoberfest2022

#25 adityabhatt branch created and added arrays folder
  arrays/.vscode/settings.json
  arrays/set_matrix_zero.cpp
  arrays/set_matrix_zero.exe
Labels: hactoberfest-accepted, hactoberfest2022, developer

#24 BoggleSolver
  SolveBoggle/Main.java
Labels: hactoberfest-accepted, hactoberfest2022

#26 Adding calculator app in python
  Calculator/calculator.py
Labels: hactoberfest-accepted, hactoberfest2022

#31 Added evaluate_postfix.cpp
  DS/stacks/evaluate_postfix.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#32 Linked Lists
  DS/linked lists/cll.cpp
  DS/linked lists/cll.exe
  DS/linked lists/dll.cpp
  DS/linked lists/dll.exe
  DS/linked lists/ll.cpp
  DS/linked lists/ll.exe
Labels: hactoberfest-accepted, hactoberfest2022

#41 created HTML/CSS projects folder
  HTML and CSS Projects/Digital Clock/app.js
  HTML and CSS Projects/Digital Clock/index.html
  HTML and CSS Projects/Quiz/app.js
  HTML and CSS Projects/Quiz/index.html
  HTML and CSS Projects/To-Do-List/app.js
  HTML and CSS Projects/To-Do-List/index.html
  HTML and CSS Projects/To-Do-List/styles.css
Labels: hactoberfest-accepted, hactoberfest2022

#45 Binary Trees and Binary Search Trees folders added
  DS/binary search trees/intro.cpp
  DS/binary trees/.vscode/settings.json
  DS/binary trees/intro.cpp
  DS/binary trees/intro.exe
Labels: hactoberfest-accepted, hactoberfest2022

#47 Main
  Contribution list.md
  Hello.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#49 Merge sort algo in the repo...
  DSA algoriths/mergeSort.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#46 Portfolio Project by Akash
  HTML and CSS Projects/portfolio/Images/andy-vult-t-WkBEOQngs-unsplash.jpg
  HTML and CSS Projects/portfolio/Images/simplee.jpg
  HTML and CSS Projects/portfolio/index.html
  HTML and CSS Projects/portfolio/script.js
  HTML and CSS Projects/portfolio/style.css
Labels: hactoberfest-accepted, hactoberfest2022

#44 Create CycleInUndirectedGraph.cpp
  DSA algoriths/CycleInUndirectedGraph.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#42 latest updated
  Graphs/BFS.cpp
  Graphs/DFS.cpp
  Graphs/Disjisktra.cpp
  Graphs/Tarjan_Algorithm.cpp
  Graphs/check_star_graph.cpp
  Graphs/kruskals.cpp
  Leetcode
  Searching-Algo/binarysearch.cpp
  Searching-Algo/linearsearch.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#39 My-new-branch
  Sorting/.vscode/c_cpp_properties.json
  Sorting/.vscode/launch.json
  Sorting/.vscode/settings.json
  Sorting/shell_sort.py
Labels: hactoberfest-accepted, hactoberfest2022

#38 added bubble sort c++ program
  DSA algoriths/demonstratethebubblesort.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#37 added python voice assistant
  voice assistant in python/jarnet.py
Labels: hactoberfest-accepted, hactoberfest2022, developer

#36 Added Occurence_of_annagram.cpp
  .vscode/settings.json
  DS/stacks/occurence_of_annagrams.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#34 Added basic C++ codes
  C++/DataTypes.cpp
  C++/Function.cpp
  C++/HelloWorld.cpp
  C++/Loops.cpp
  C++/Recursion.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#53 My html, css project
  HTML and CSS Projects/ColourFlipper/README.md
  HTML and CSS Projects/ColourFlipper/app.js
  HTML and CSS Projects/ColourFlipper/index.html
  HTML and CSS Projects/ColourFlipper/style.css
Labels: hactoberfest-accepted, hactoberfest2022

#52 Create HTML and CSS
  HTML and CSS
Labels: hactoberfest-accepted, hactoberfest2022

#54 binary_search.py file created
  C++/postfix_evaluation/evaluate_postfix.cpp
  Searching-Algo/binary_Search.py
Labels: hactoberfest-accepted, hactoberfest2022

#67 Mouse movement tracking is added
  eyedoodle.html
Labels: hactoberfest-accepted, hactoberfest2022

#66 ML models minist
  ML Projects/Minist/minist training.ipynb
  ML Projects/Minist/mnist.h5
Labels: hactoberfest-accepted, hactoberfest2022

#65 Created a simple Navbar project
  HTML and CSS Projects/navbar/README.md
  HTML and CSS Projects/navbar/app.js
  HTML and CSS Projects/navbar/index.html
  HTML and CSS Projects/navbar/style.css
Labels: hactoberfest-accepted, hactoberfest2022

#63 Python Kilometers to meters
  Python/km_to_m.py
Labels: hactoberfest-accepted, hactoberfest2022

#78 Create C++ program for Dijkstra's single source shortest path
  C++/C++ program for Dijkstra's single source shortest path
Labels: hactoberfest-accepted, hactoberfest2022

#77 Responsive Contact Us Page
  HTML and CSS Projects/Responsive Contact Us Page/bg.jpg
  HTML and CSS Projects/Responsive Contact Us Page/index.html
  HTML and CSS Projects/Responsive Contact Us Page/style.css
Labels: hactoberfest-accepted, hactoberfest2022

#62 HacktoberFest2022
  C++/kth_ele_of_array.cpp
Labels: documentation, hactoberfest-accepted, hactoberfest2022

#69 Adding An beginner friendly IOT project
  IOT projects/Smoke Detector/CktDiagram.png
  IOT projects/Smoke Detector/Code/Code.ino
  IOT projects/Smoke Detector/arduiniunojpeg.jpg
  IOT projects/Smoke Detector/breadboard.jpg
  IOT projects/Smoke Detector/gasSensor.jpg
  IOT projects/Smoke Detector/readme.md
  IOT projects/Smoke Detector/temperatureSensor.jpg
Labels: good first issue, hactoberfest-accepted, hactoberfest2022, IOT

#68 Create countgoodtriplet.cpp
  countgoodtriplet.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#74 Create palindrome.cpp
  DSA algoriths/palindrome.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#82 Create palindrome.js
  javascript/palindrome.js
Labels: hactoberfest-accepted, hactoberfest2022

#103 added algorithms
  C++/HreturnPermutationOfString.cpp
  HprintSubsetOfArray.cpp
  HreturnAllCodes.cpp
  HreturnsubsetOfArray.cpp
Labels: hactoberfest-accepted, hactoberfest2022

#96 Rock paper scissors
  Python/rock_paper_scissors.py
Labels: hactoberfest-accepted, hactoberfest2022

#93 Create snake-water-gun.py
  Python/snake-water-gun.py
Labels: hactoberfest-accepted, hactoberfest2022

#95 added mini number game java
  java/HiddenNumber.java
Labels: hactoberfest-accepted, hactoberfest2022

#89 Create DP_Series_Rod_Cutting
  C++/DP_Series_Rod_Cutting
Labels: hactoberfest-accepted, hactoberfest2022

#112 Create tictactoe.java
  java/tictactoe.java
Labels: hactoberfest-accepted, hactoberfest2022

#113 Created swap.c
  swap.c
Labels: hactoberfest-accepted, hactoberfest2022

#115 Create ml beginner learnings
  ml beginner learnings
Labels: hactoberfest-accepted, hactoberfest2022, Machine Learning
